language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: hzqor30+AcctdpcHKMDakUdTL/QusWqH4dniYBJSO6ugtgTrj+kNfGh+sCKs0jGGhshz15ZTU2PsO6AtQufcskBcmwoZo83Cteb9dkLHjHwaWLV3DJtYXztKcooFQEM2rRLdJMG+CXb7lLoxEFTJ219TykewWfFiAlqazPrfu/BAxiC/iSQqctaY69fqHOIKaUxhKwnxCavJnexddXkTy8+24Bdxg9XlVAUoVrUN7t8KkShwQJ6WnkxAkiXqsxoBylMdxcdSGNH9LI20JCKmTdBJF/gckay/O7kdDa367XhKT6Fcjwd9smoBToS6Wi8nFlcJ367UL9jDrWjMhAhO4TjVbItYQm74IUXv5yhJhw2X8VO/yawtRjLNQkT4tChc6FfvPnfU/R246CPf9ShrmTkDU2h0cTvw8yyzIYJDsB/cyVBDTG5FuBowLT9M2OCScBHyqKVmhZEa7jZk9qGLXH5057EXhbDVdwR3lWLdXnQ3gmaMIeaO/BOQxdP43XixYb7kvHQ0OqpgmyRA701FRDi2h/2z1ALAVmMmfAZsOs+tN/KiiWPthH7QN2daojWqYpHinQZ3y8PFaQiuNasiO0hVXIrPJDMKfTu2Oc+ok5gEN85LDQtBZV8UwuGcCiCj7h1khf8rvdu8+vT8WtLpB5xmrbcJScpQC0v1lcmiPgo=
  app: noteful-hiram
  on:
    repo: thinkful-ei20/hiram-noteful-v1
